server:
    port: 80

spring:
    logging:
        level:
            me.jincrates: DEBUG

    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                default_batch_fetch_size: 1000
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.H2Dialect

    devtools:
        livereload:
            enabled: true
