server:
    port: 9001

spring:
    application:
        name: client-service

eureka:
    client:
        register-with-eureka: true
        fetch-register: true  # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka  # ??? ??? ?? ???? ??
