
#?????? ?? ??
server:
    port: 8080

spring:
    devtools:
        livereload:
            enabled: true
    h2:
        console:
            enabled: true

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.H2Dialect

    # ??? ???? ???? ??? ???? ??
    logging:
        level:
            org:
                hibernate:
                    type:
                        descriptor:
                            sql: trace

    thymeleaf:
        cache: false
        # check-template-location: true
        # prefix: classpath:/templates/