server:
    port: 8080

spring:
    devtools:
        livereload:
            enabled: true
    h2:
        console:
            enabled: true
#    datasource:
#        url: jdbc:h2:mem:testdb
#        driverClassName: org.h2.Driver
#        username: sa
#        password:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shop
        username: bootuser
        password: bootuser

    jpa:
        hibernate:
            ddl-auto: update  #validate
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQL5Dialect

    logging:
        level:
            org:
                hibernate:
                    type:
                        descriptor:
                            sql: trace

    thymeleaf:
        cache: false

    servlet:
        multipart:
            maxFileSize: 20MB
            maxRequestSize: 100MB

itemImgLocation: /Users/jincrates/projects/upload/shop/item # C:/shop/item
uploadPath: file:///Users/jincrates/projects/upload/shop/  #file:///C:/shop/



