server:
    port: 8080

spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
#
#    datasource:
#        url: jdbc:h2:mem:testdb
#        driverClassName: org.h2.Driver
#        username: sa
#        password:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/work-manage
        username: bootuser
        password: bootuser
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true
    logging:
        level:
            me.jincrates: DEBUG