server:
    port: 8080

spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/work-manage
        username: bootuser
        password: bootuser
    jpa:
        properties:
            dialect: org.hibernate.dialect.MySQLDialect
            hibernate:
                format_sql: true
                ddl-auto: update #create-drop
                show-sql: true
    logging:
        level:
            me.jincrates: DEBUG