spring:
    jackson:
        serialization:
            fail-on-empty-beans: false

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false

    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true

