spring:
    profiles:
        include: oauth, real-db

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                show_sql: true
    h2:
        console:
            enabled: true
    session:
        store-type: jdbc