spring:
    profiles:
        include: oauth

    mustache:
        suffix: .html
        prefix: classpath:/templates/

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true

    h2:
        console:
            enabled: true

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:

    session:
        store-type: jdbc

    logging:
        level:
            me.jincrates: DEBUG