spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 클라이언트ID
                        client-secret: 클라이언트Secret
                        scope: profile,email
                    naver:
                        client-id: 클라이언트ID
                        client-secret: 클라이언트Secret
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        authorization-grant-type: authorization_code
                        scope: name, email, profile_image
                        client-name: Naver
                    kakao:
                        client-id: 클라이언트ID
                        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                        client-authentication-method: POST
                        authorization-grant-type: authorization_code
                        scope: profile_nickname, profile_image, account_email
                        client-name: Kakao
                provider:
                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response
                    kakao:
                        authorization_uri: https://kauth.kakao.com/oauth/authorize
                        token_uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user_name_attribute: id
