server:
    port: 8761  #Eureka ???? ??? ??

spring:
    application:
        name: discoveryservice  #???? ??? ?? id

eureka:
    client:
        register-with-eureka: false  #?? ??? ???? ??
        fetch-registry: false  #?? ??? ???? ??
