server:
    port: 8080

spring:
    h2:
        console:
            enabled: true
#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/gobook
#        username: bootuser
#        password: bootuser
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://springboot-blog.cbwrekiqrow4.ap-northeast-2.rds.amazonaws.com:3306/gobook
        username: jincrates
        password: jincrates

    jpa:
        hibernate:
            ddl-auto: node
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                default_batch_fetch_size: 1000

    devtools:
        livereload:
            enabled: true

    servlet:
        multipart:
            maxFileSize: 20MB
            maxRequestSize: 100MB

    logging:
        level:
            me.jincrates: DEBUG

#itemImgLocation: /Users/jincrates/projects/upload/shop/item # C:/shop/item
#uploadPath: file:///Users/jincrates/projects/upload/shop/  #file:///C:/shop/
itemImgLocation: /home/ec2-user/upload/gobook/item
uploadPath: file:///home/ec2-user/upload/gobook/