////SELECT B.MONTH, A.NAME, B.COUNT
////        FROM PLACES A
////        INNER JOIN (
////        SELECT PLACE_ID, MONTH(CREATED_AT) AS MONTH, COUNT(COMMENTS) AS COUNT
////        FROM PLACE_REVIEWS
////        WHERE CREATED_AT BETWEEN '2018-01-01' AND '2018-12-31'
////        GROUP BY PLACE_ID, MONTH(CREATED_AT)
////        ) B ON A.ID = B.PLACE_ID
////        ORDER BY B.MONTH, A.NAME
//
//
//
//
//-- 2018-01-01 ~ 2018-12-31
//        -- 월별로 후기가 가장 많은 공간의 이름과 후기의 수
//        -- 결과는 월별로 오름차순, 그 다음은 공간의 이름 순서
//
///*
//SELECT ID
//
//SELECT ID
//     , PLACE_ID
//     , CREATED_AT
//     , REVIEWER_ID
//     , MAX(COMMENTS)
//
//SELECT MONTH(CREATED_AT) AS MONTH, COUNT(COMMENTS) AS CNT
//FROM PLACE_REVIEWS
//WHERE CREATED_AT BETWEEN '2018-01-01' AND '2018-12-31'
//GROUP BY MONTH(CREATED_AT), COMMENTS
//*/
///*
//SELECT A.ID
//     , MONTH(B.CREATED_AT)
//     , COUNT(B.COMMENTS)
//FROM PLACES AS A
//INNER JOIN PLACE_REVIEWS AS B ON A.ID = B.PLACE_ID
//WHERE B.CREATED_AT BETWEEN '2018-01-01' AND '2018-12-31'
//GROUP BY A.ID, MONTH(B.CREATED_AT), B.COMMENTS
//*/
//
///*
//SELECT B.MONTH, A.NAME, B.COUNT
//FROM PLACES A
//INNER JOIN (
//    SELECT PLACE_ID, MONTH(CREATED_AT) AS MONTH, COUNT(COMMENTS) AS COUNT
//    FROM PLACE_REVIEWS
//    WHERE CREATED_AT BETWEEN '2018-01-01' AND '2018-12-31'
//    GROUP BY PLACE_ID, MONTH(CREATED_AT)
//) B ON A.ID = B.PLACE_ID
//ORDER BY B.MONTH, A.NAME
//*/
//
//        SELECT B.MONTH, A.NAME, B.COUNT
//        FROM PLACES A
//        INNER JOIN (
//        SELECT A.PLACE_ID, MONTH, COUNT
//        , RANK() OVER(PARTITION BY MONTH ORDER BY COUNT DESC) AS RANK_NO
//        FROM (
//        SELECT PLACE_ID
//        , MONTH(CREATED_AT) AS MONTH
//        , COUNT(COMMENTS) AS COUNT
//        FROM PLACE_REVIEWS
//        WHERE CREATED_AT BETWEEN '2018-01-01' AND '2018-12-31'
//        GROUP BY PLACE_ID, MONTH(CREATED_AT)
//        ) A
//        ) B ON A.ID = B.PLACE_ID
//        WHERE RANK_NO = 1
//        ORDER BY B.MONTH, A.NAME
//
//*/